### ISSUE TITLE
Fail to load in Logic 1.2.18, while success in Logic 2.4.7

### ISSUE THREAD

**Issue by studyletmefeelwuhu** [saleae/serial-analyzer#13]
I  have seen a setting parameter in "CMakeLists.txt" called "-DLOGIC2", does it only work for Logic 2.x? And some classes like "FrameV2" mean the same thing?

**Comment by timreyes** [comment]
I posted a reply here that relates to this post as well.
https://github.com/saleae/SampleAnalyzer/issues/26

As such, I'll close this issue report for now, but I'd love to hear from you via email in case you'd like to continue chatting about this.
